# generate with `builder --config .otelcol-builder.yaml`
dist:
    module: github.com/maticnetwork/polygon-otel-collector # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
    name: polygon-otel-collector # the binary name. Optional.
    description: "Polygon OpenTelemetry Collector distribution" # a long name for the application. Optional.
    otelcol_version: "0.44.0" # the OpenTelemetry Collector version to use as base for the distribution. Optional.
    output_path: ./ # the path to write the output (sources and binary). Optional.
    version: "1.0.0" # the version for your custom OpenTelemetry Collector. Optional.
exporters:
  - gomod: "github.com/maticnetwork/polygon-otel-collector/receiver/polygonreceiver main" # the Go module for the component. Required.
    name: "polygonreceiver" # package name to use in the generated sources. Optional.
replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
