receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680
  polygon:

processors:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - logging
    metrics:
      receivers:
        - polygon
      processors: []
      exporters:
        - logging
