// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/maticnetwork/polygon-otel-collector

go 1.17

require (
	github.com/maticnetwork/polygon-otel-collector/receiver/polygonreceiver main
	go.opentelemetry.io/collector v0.44.0
)

