receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

  polygon:

  influxdb:

processors:

exporters:
  logging:
    loglevel: debug

  datadog:
    api:
      key: "${POLYGON_OTEL_COLLECTOR_DD_API_KEY}"

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - logging
    metrics:
      receivers:
        - influxdb
      processors: []
      exporters:
        - logging
        - datadog
