// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/model/pdata"
)

// MetricSettings provides common settings for a particular metric.
type MetricSettings struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsSettings provides settings for polygonreceiver metrics.
type MetricsSettings struct {
	PolygonCheckpointValidatorsSigned MetricSettings `mapstructure:"polygon.checkpoint_validators_signed"`
	PolygonHeimdallTotalTxs           MetricSettings `mapstructure:"polygon.heimdall.total_txs"`
	PolygonHeimdallUnconfirmedTxs     MetricSettings `mapstructure:"polygon.heimdall.unconfirmed_txs"`
	PolygonLastBlock                  MetricSettings `mapstructure:"polygon.last_block"`
	PolygonLastBlockTime              MetricSettings `mapstructure:"polygon.last_block_time"`
	PolygonSubmitCheckpointTime       MetricSettings `mapstructure:"polygon.submit_checkpoint_time"`
}

func DefaultMetricsSettings() MetricsSettings {
	return MetricsSettings{
		PolygonCheckpointValidatorsSigned: MetricSettings{
			Enabled: true,
		},
		PolygonHeimdallTotalTxs: MetricSettings{
			Enabled: true,
		},
		PolygonHeimdallUnconfirmedTxs: MetricSettings{
			Enabled: true,
		},
		PolygonLastBlock: MetricSettings{
			Enabled: true,
		},
		PolygonLastBlockTime: MetricSettings{
			Enabled: true,
		},
		PolygonSubmitCheckpointTime: MetricSettings{
			Enabled: true,
		},
	}
}

type metricPolygonCheckpointValidatorsSigned struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.checkpoint_validators_signed metric with initial data.
func (m *metricPolygonCheckpointValidatorsSigned) init() {
	m.data.SetName("polygon.checkpoint_validators_signed")
	m.data.SetDescription("Number of validators who signed last checkpoint.")
	m.data.SetUnit("")
	m.data.SetDataType(pdata.MetricDataTypeGauge)
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonCheckpointValidatorsSigned) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val int64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonCheckpointValidatorsSigned) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonCheckpointValidatorsSigned) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonCheckpointValidatorsSigned(settings MetricSettings) metricPolygonCheckpointValidatorsSigned {
	m := metricPolygonCheckpointValidatorsSigned{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

type metricPolygonHeimdallTotalTxs struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.heimdall.total_txs metric with initial data.
func (m *metricPolygonHeimdallTotalTxs) init() {
	m.data.SetName("polygon.heimdall.total_txs")
	m.data.SetDescription("Total number of transactions.")
	m.data.SetUnit("txs")
	m.data.SetDataType(pdata.MetricDataTypeGauge)
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonHeimdallTotalTxs) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val int64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonHeimdallTotalTxs) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonHeimdallTotalTxs) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonHeimdallTotalTxs(settings MetricSettings) metricPolygonHeimdallTotalTxs {
	m := metricPolygonHeimdallTotalTxs{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

type metricPolygonHeimdallUnconfirmedTxs struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.heimdall.unconfirmed_txs metric with initial data.
func (m *metricPolygonHeimdallUnconfirmedTxs) init() {
	m.data.SetName("polygon.heimdall.unconfirmed_txs")
	m.data.SetDescription("Number of unconfirmed transactions.")
	m.data.SetUnit("txs")
	m.data.SetDataType(pdata.MetricDataTypeGauge)
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonHeimdallUnconfirmedTxs) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val int64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonHeimdallUnconfirmedTxs) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonHeimdallUnconfirmedTxs) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonHeimdallUnconfirmedTxs(settings MetricSettings) metricPolygonHeimdallUnconfirmedTxs {
	m := metricPolygonHeimdallUnconfirmedTxs{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

type metricPolygonLastBlock struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.last_block metric with initial data.
func (m *metricPolygonLastBlock) init() {
	m.data.SetName("polygon.last_block")
	m.data.SetDescription("The current block number.")
	m.data.SetUnit("block")
	m.data.SetDataType(pdata.MetricDataTypeSum)
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pdata.MetricAggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonLastBlock) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val int64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonLastBlock) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonLastBlock) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonLastBlock(settings MetricSettings) metricPolygonLastBlock {
	m := metricPolygonLastBlock{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

type metricPolygonLastBlockTime struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.last_block_time metric with initial data.
func (m *metricPolygonLastBlockTime) init() {
	m.data.SetName("polygon.last_block_time")
	m.data.SetDescription("The average block time.")
	m.data.SetUnit("milliseconds")
	m.data.SetDataType(pdata.MetricDataTypeGauge)
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonLastBlockTime) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val int64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonLastBlockTime) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonLastBlockTime) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonLastBlockTime(settings MetricSettings) metricPolygonLastBlockTime {
	m := metricPolygonLastBlockTime{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

type metricPolygonSubmitCheckpointTime struct {
	data     pdata.Metric   // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills polygon.submit_checkpoint_time metric with initial data.
func (m *metricPolygonSubmitCheckpointTime) init() {
	m.data.SetName("polygon.submit_checkpoint_time")
	m.data.SetDescription("Latest checkpoint transaction time.")
	m.data.SetUnit("seconds")
	m.data.SetDataType(pdata.MetricDataTypeGauge)
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPolygonSubmitCheckpointTime) recordDataPoint(start pdata.Timestamp, ts pdata.Timestamp, val float64, chainAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleVal(val)
	dp.Attributes().Insert(A.Chain, pdata.NewAttributeValueString(chainAttributeValue))
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPolygonSubmitCheckpointTime) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPolygonSubmitCheckpointTime) emit(metrics pdata.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPolygonSubmitCheckpointTime(settings MetricSettings) metricPolygonSubmitCheckpointTime {
	m := metricPolygonSubmitCheckpointTime{settings: settings}
	if settings.Enabled {
		m.data = pdata.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user settings.
type MetricsBuilder struct {
	startTime                               pdata.Timestamp
	metricPolygonCheckpointValidatorsSigned metricPolygonCheckpointValidatorsSigned
	metricPolygonHeimdallTotalTxs           metricPolygonHeimdallTotalTxs
	metricPolygonHeimdallUnconfirmedTxs     metricPolygonHeimdallUnconfirmedTxs
	metricPolygonLastBlock                  metricPolygonLastBlock
	metricPolygonLastBlockTime              metricPolygonLastBlockTime
	metricPolygonSubmitCheckpointTime       metricPolygonSubmitCheckpointTime
}

// metricBuilderOption applies changes to default metrics builder.
type metricBuilderOption func(*MetricsBuilder)

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pdata.Timestamp) metricBuilderOption {
	return func(mb *MetricsBuilder) {
		mb.startTime = startTime
	}
}

func NewMetricsBuilder(settings MetricsSettings, options ...metricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		startTime:                               pdata.NewTimestampFromTime(time.Now()),
		metricPolygonCheckpointValidatorsSigned: newMetricPolygonCheckpointValidatorsSigned(settings.PolygonCheckpointValidatorsSigned),
		metricPolygonHeimdallTotalTxs:           newMetricPolygonHeimdallTotalTxs(settings.PolygonHeimdallTotalTxs),
		metricPolygonHeimdallUnconfirmedTxs:     newMetricPolygonHeimdallUnconfirmedTxs(settings.PolygonHeimdallUnconfirmedTxs),
		metricPolygonLastBlock:                  newMetricPolygonLastBlock(settings.PolygonLastBlock),
		metricPolygonLastBlockTime:              newMetricPolygonLastBlockTime(settings.PolygonLastBlockTime),
		metricPolygonSubmitCheckpointTime:       newMetricPolygonSubmitCheckpointTime(settings.PolygonSubmitCheckpointTime),
	}
	for _, op := range options {
		op(mb)
	}
	return mb
}

// Emit appends generated metrics to a pdata.MetricsSlice and updates the internal state to be ready for recording
// another set of data points. This function will be doing all transformations required to produce metric representation
// defined in metadata and user settings, e.g. delta/cumulative translation.
func (mb *MetricsBuilder) Emit(metrics pdata.MetricSlice) {
	mb.metricPolygonCheckpointValidatorsSigned.emit(metrics)
	mb.metricPolygonHeimdallTotalTxs.emit(metrics)
	mb.metricPolygonHeimdallUnconfirmedTxs.emit(metrics)
	mb.metricPolygonLastBlock.emit(metrics)
	mb.metricPolygonLastBlockTime.emit(metrics)
	mb.metricPolygonSubmitCheckpointTime.emit(metrics)
}

// RecordPolygonCheckpointValidatorsSignedDataPoint adds a data point to polygon.checkpoint_validators_signed metric.
func (mb *MetricsBuilder) RecordPolygonCheckpointValidatorsSignedDataPoint(ts pdata.Timestamp, val int64, chainAttributeValue string) {
	mb.metricPolygonCheckpointValidatorsSigned.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// RecordPolygonHeimdallTotalTxsDataPoint adds a data point to polygon.heimdall.total_txs metric.
func (mb *MetricsBuilder) RecordPolygonHeimdallTotalTxsDataPoint(ts pdata.Timestamp, val int64, chainAttributeValue string) {
	mb.metricPolygonHeimdallTotalTxs.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// RecordPolygonHeimdallUnconfirmedTxsDataPoint adds a data point to polygon.heimdall.unconfirmed_txs metric.
func (mb *MetricsBuilder) RecordPolygonHeimdallUnconfirmedTxsDataPoint(ts pdata.Timestamp, val int64, chainAttributeValue string) {
	mb.metricPolygonHeimdallUnconfirmedTxs.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// RecordPolygonLastBlockDataPoint adds a data point to polygon.last_block metric.
func (mb *MetricsBuilder) RecordPolygonLastBlockDataPoint(ts pdata.Timestamp, val int64, chainAttributeValue string) {
	mb.metricPolygonLastBlock.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// RecordPolygonLastBlockTimeDataPoint adds a data point to polygon.last_block_time metric.
func (mb *MetricsBuilder) RecordPolygonLastBlockTimeDataPoint(ts pdata.Timestamp, val int64, chainAttributeValue string) {
	mb.metricPolygonLastBlockTime.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// RecordPolygonSubmitCheckpointTimeDataPoint adds a data point to polygon.submit_checkpoint_time metric.
func (mb *MetricsBuilder) RecordPolygonSubmitCheckpointTimeDataPoint(ts pdata.Timestamp, val float64, chainAttributeValue string) {
	mb.metricPolygonSubmitCheckpointTime.recordDataPoint(mb.startTime, ts, val, chainAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...metricBuilderOption) {
	mb.startTime = pdata.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op(mb)
	}
}

// Attributes contains the possible metric attributes that can be used.
var Attributes = struct {
	// Chain (The name of a chain.)
	Chain string
}{
	"chain",
}

// A is an alias for Attributes.
var A = Attributes
